CREATE TABLE USERS
(
  USER_ID       LONG               NOT NULL AUTO_INCREMENT
    primary key,
  LOGIN         VARCHAR(20) UNIQUE NOT NULL,
  EMAIL         VARCHAR(60) UNIQUE NOT NULL,
  USER_ROLE     VARCHAR(20)        NOT NULL,
  USER_PASSWORD VARCHAR(128)       NOT NULL
);

CREATE TABLE COURSES
(
  COURSE_ID          LONG AUTO_INCREMENT
    primary key,
  COURSE_DESCRIPTION VARCHAR(300),
);

CREATE TABLE TESTS
(
  TEST_ID          LONG not null AUTO_INCREMENT
    primary key,
  COURSE_ID        LONG
  constraint PARENT_COURSE
  references COURSES,
  TEST_DESCRIPTION VARCHAR(120),
);

CREATE TABLE QUESTIONS
(
  QUESTION_ID      LONG NOT NULL AUTO_INCREMENT
    primary key,
  TEST_ID          LONG,
  QUESTION         VARCHAR(600),
  ANSWER_NO_OPTION VARCHAR(20),
  QUESTION_TYPE    VARCHAR(20),
  FOREIGN KEY (TEST_ID) REFERENCES TESTS (TEST_ID)
);

CREATE TABLE OPTION_OF_ANSWER
(
  OPTION_ID           LONG NOT NULL AUTO_INCREMENT
    primary key,
  QUESTION_ID         LONG
    constraint OPTION_FOR_QUESTION
    references QUESTIONS,
  OPTION_TEXT         VARCHAR(120),
  IS_CORRECT          BOOLEAN       default false,
  IS_SEQUENCE_BASED   BOOLEAN       default false,
  NUMBERS_IN_SEQUENCE LONG          DEFAULT 0
);

CREATE TABLE SUBSCRIPTIONS
(
  SUBSCRIPTION_ID LONG not null AUTO_INCREMENT
    primary key,
  USER_ID         LONG NOT NULL
    constraint FK_SUBSCRIBED_USER
    references USERS,
  COURSE_ID       LONG NOT NULL
    constraint FK_SUBSCRIBED_COURSE
    references COURSES,
  TEST_STATUS     VARCHAR(30)
);