CREATE TABLE USERS
(
  USER_ID       INT NOT NULL AUTO_INCREMENT
    primary key,
  LOGIN         VARCHAR(20) UNIQUE NOT NULL ,
  EMAIL         VARCHAR(60) UNIQUE NOT NULL ,
  USER_ROLE     VARCHAR (20) NOT NULL,
  USER_PASSWORD VARCHAR(128) NOT NULL
);

CREATE TABLE COURSES
(
  COURSE_ID          INT AUTO_INCREMENT
    primary key,
  COURSE_DESCRIPTION VARCHAR(300),
);

CREATE TABLE QUESTIONS
(
  QUESTION_ID    INT NOT NULL AUTO_INCREMENT
    primary key ,
  QUESTION          VARCHAR(600),
  ANSWER_NO_OPTION  VARCHAR(20),
  QUESTION_TYPE  VARCHAR(20),
);

CREATE TABLE OPTION_OF_ANSWER
(
  OPTION_ID   INT NOT NULL AUTO_INCREMENT
    primary key,
  QUESTION_ID INT
    constraint OPTION_FOR_QUESTION
    references QUESTIONS,
  OPTION_TEXT VARCHAR(120),
  IS_CORRECT   BOOLEAN default false,
  IS_SEQUENCE_BASED   BOOLEAN default false,
  NUMBERS_IN_SEQUENCE INT DEFAULT 0
);

CREATE TABLE SUBSCRIPTIONS
(
  id int not null AUTO_INCREMENT
    primary key,
  USER_ID     INT NOT NULL
    constraint FK_SUBSCRIBED_USER
    references USERS,
  COURSE_ID   INTEGER not null
    constraint FK_SUBSCRIBED_COURSE
    references COURSES,
  TEST_STATUS VARCHAR(30)
);

CREATE TABLE TESTS
(
  COURSE_ID     INT NOT NULL,
  QUESTION_ID   INT NOT NULL,
  CONSTRAINT TEST_PK PRIMARY KEY (COURSE_ID,QUESTION_ID),
  CONSTRAINT FK_Question FOREIGN KEY (QUESTION_ID)
  REFERENCES QUESTIONS (QUESTION_ID),
  CONSTRAINT FK_QuestionCOURSE FOREIGN KEY (COURSE_ID)
  REFERENCES COURSES (COURSE_ID)
);



